In [1]:
!pip install spacy

In [2]:

import spacy
!python -m spacy download en_core_web_lg



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 4.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [3]:
nlp=spacy.load('en_core_web_lg')

In [4]:
doc=nlp("dog cat banana")

In [5]:
for token in doc:
  print(token.text)

dog
cat
banana


In [6]:
#let i will add one word which is not there in english word
doc=nlp("dog cat banana elavunnav")

In [7]:
for token in doc:#elavunna is out of vocabulary
  print(token.text,"vector:",token.has_vector)#here we can see elavunnav vector is not present in english dictionary

dog vector: True
cat vector: True
banana vector: True
elavunnav vector: False


In [8]:
#checking elavunna is out of vocabulary
for token in doc:
  print(token.text,"vector:",token.has_vector,"   OOV:",token.is_oov)#here we can see elavunnav vector is not present in english dictionary so it is out of vocabulary

dog vector: True    OOV: False
cat vector: True    OOV: False
banana vector: True    OOV: False
elavunnav vector: False    OOV: True


In [9]:
doc[0].vector

array([-4.0176e-01,  3.7057e-01,  2.1281e-02, -3.4125e-01,  4.9538e-02,
        2.9440e-01, -1.7376e-01, -2.7982e-01,  6.7622e-02,  2.1693e+00,
       -6.2691e-01,  2.9106e-01, -6.7270e-01,  2.3319e-01, -3.4264e-01,
        1.8311e-01,  5.0226e-01,  1.0689e+00,  1.4698e-01, -4.5230e-01,
       -4.1827e-01, -1.5967e-01,  2.6748e-01, -4.8867e-01,  3.6462e-01,
       -4.3403e-02, -2.4474e-01, -4.1752e-01,  8.9088e-02, -2.5552e-01,
       -5.5695e-01,  1.2243e-01, -8.3526e-02,  5.5095e-01,  3.6410e-01,
        1.5361e-01,  5.5738e-01, -9.0702e-01, -4.9098e-02,  3.8580e-01,
        3.8000e-01,  1.4425e-01, -2.7221e-01, -3.7016e-01, -1.2904e-01,
       -1.5085e-01, -3.8076e-01,  4.9583e-02,  1.2755e-01, -8.2788e-02,
        1.4339e-01,  3.2537e-01,  2.7226e-01,  4.3632e-01, -3.1769e-01,
        7.9405e-01,  2.6529e-01,  1.0135e-01, -3.3279e-01,  4.3117e-01,
        1.6687e-01,  1.0729e-01,  8.9418e-02,  2.8635e-01,  4.0117e-01,
       -3.9222e-01,  4.5217e-01,  1.3521e-01, -2.8878e-01, -2.28

In [10]:
doc[0].vector.shape#it is 300 dimensions vector we can represent dog word in 300 dimensions

(300,)

In [11]:
doc[3].vector #here elavunnav is oov so all are zeo here

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [12]:
base_token=nlp("sandwich")
base_token.vector.shape

(300,)

In [13]:
import spacy


nlp = spacy.load('en_core_web_lg')

#similarity checking
doc = nlp("bread sandwich burger car tiger human rice food")  # Process the text with nlp
print(doc)
for token in doc:
  print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

bread sandwich burger car tiger human rice food
bread <-> sandwich: 0.6874560117721558
sandwich <-> sandwich: 1.0
burger <-> sandwich: 0.767081618309021
car <-> sandwich: 0.1664874404668808
tiger <-> sandwich: 0.1713561713695526
human <-> sandwich: 0.14466442167758942
rice <-> sandwich: 0.46796026825904846
food <-> sandwich: 0.5090628862380981


In [14]:
king=nlp.vocab["king"].vector
man=nlp.vocab["man"].vector
woman=nlp.vocab["woman"].vector
queen=nlp.vocab["queen"].vector
result=king-man+woman

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([result],[queen])

array([[0.78808445]], dtype=float32)

In [15]:
import pandas as pd
df=pd.read_csv("//content//fake_or_real_news.csv")

In [16]:
df

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

In [17]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [18]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [19]:
df.shape

(6335, 4)

In [25]:
df['title'][0]

'You Can Smell Hillary’s Fear'

In [26]:
df['text'][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [27]:
df['label'].value_counts()

label
REAL    3171
FAKE    3164
Name: count, dtype: int64

In [29]:
df['label_encoded'] = df['label'].map({'FAKE': 0, 'REAL': 1})


In [30]:
df

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  label_encoded  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE              0  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE              0  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL              1  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE              0  
4     It's primary day in New York and front-runners...  REAL              1  
...                                                 ...   ...            ...  
6330  The State Department told the Republican Natio...  REAL              1  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE              0  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE              0  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL              1  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL              1  

[6335 rows x 5 columns]

In [31]:

import spacy
!python -m spacy download en_core_web_lg



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 1.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [32]:
nlp=spacy.load('en_core_web_lg')

In [33]:
#now converting whole text to vector
#df['title_vector']=df['title'].apply(lambda x:nlp(x).vector)
df['text_vector']=df['text'].apply(lambda y:nlp(y).vector)

In [34]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  label_encoded  \
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE              0   
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE              0   
2  U.S. Secretary of State John F. Kerry said Mon...  REAL              1   
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE              0   
4  It's primary day in New York and front-runners...  REAL              1   

                                        title_vector  \
0  [-0.19751866, 0.15755266, -0.171201, 0.031315,...   
1  [-0.09375132, 0.11547916, 0.03717506, 0.117533...   
2  [-0.015284108, 0.11492733, -0.061525557, 0.020...   
3  [-0.055520147, 0.14451094, -0.07738895, -0.011...   
4  [0.0050000013, 0.12225419, -0.09032141, -0.125...   

                                         text_vector  
0  [-0.06343732, 0.11896122, -0.067684345, -0.018...  
1  [-0.017111547, 0.13953958, -0.05576232, 0.0063...  
2  [-0.018148802, 0.17694649, -0.024513047, -0.04...  
3  [-0.054569427, 0.14917314, 0.0107977595, -0.00...  
4  [-0.020318953, 0.16901688, -0.041723646, -0.06...

In [75]:
import numpy as np
x=np.stack(df['text_vector'].values)
y=df['label_encoded']

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [77]:
X_train.shape

(5068, 300)

In [78]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [81]:
model=MultinomialNB()
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_stack_sc = scaler.fit_transform(X_train)
X_test_stack_sc = scaler.transform(X_test)


model.fit(X_train_stack_sc, y_train)

MultinomialNB()

In [82]:
model.score(X_train_stack_sc,y_train)

0.7760457774269929

In [83]:
y_pred=model.predict(X_test_stack_sc)

In [84]:
accuracy_score(y_test,y_pred)

0.7853196527229677